STOCKS_JSON =
    [


        {"Name": "騰訊", "Symbol": "0700", "Price": 573, "OptionMultiple": 100, "IsHK": 1}
        , {"Name": "阿里", "Symbol": "9988", "Price": 203, "OptionMultiple": 500, "IsHK": 1}
        , {"Name": "富途", "Symbol": "FUTU", "Price": 148.3, "OptionMultiple": 100, "IsHK": 0}
    ];


OPTIONS_JSON =
    [
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 240,
            "StockTicker": "",
            "DateBought": "2020/11/12 14:47",
            "DateExp": "2020-11-27",
            "Premium": 18.6,
            "AmtCost": 1860,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 205,
            "StockTicker": "",
            "DateBought": "2020/11/12 14:58",
            "DateExp": "2020-12-30",
            "Premium": 2.29,
            "AmtCost": 229,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 240,
            "StockTicker": "",
            "DateBought": "2020/11/12 15:24",
            "DateExp": "2020-11-27",
            "Premium": 18.5,
            "AmtCost": 1850,
            "NumContract": 1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 195,
            "StockTicker": "",
            "DateBought": "2020/11/13 14:36",
            "DateExp": "2021-06-29",
            "Premium": 8.89,
            "AmtCost": 2667,
            "NumContract": -3,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 620,
            "StockTicker": "",
            "DateBought": "2020/11/13 15:20",
            "DateExp": "2020-11-27",
            "Premium": 8.23,
            "AmtCost": 823,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 200,
            "StockTicker": "",
            "DateBought": "2020/11/16 10:10",
            "DateExp": "2020-12-30",
            "Premium": 2.36,
            "AmtCost": 236,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 215,
            "StockTicker": "",
            "DateBought": "2020/11/16 10:11",
            "DateExp": "2020-11-27",
            "Premium": 1.02,
            "AmtCost": 102,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 480,
            "StockTicker": "",
            "DateBought": "2020/11/16 11:52",
            "DateExp": "2021-02-25",
            "Premium": 7.58,
            "AmtCost": 758,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 180,
            "StockTicker": "",
            "DateBought": "2020/11/17 9:48",
            "DateExp": "2021-06-29",
            "Premium": 5.81,
            "AmtCost": 1162,
            "NumContract": -2,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 180,
            "StockTicker": "",
            "DateBought": "2020/11/17 9:49",
            "DateExp": "2021-06-29",
            "Premium": 5.97,
            "AmtCost": 597,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 410,
            "StockTicker": "",
            "DateBought": "2020/11/17 13:37",
            "DateExp": "2021-06-29",
            "Premium": 6.57,
            "AmtCost": 657,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 490,
            "StockTicker": "",
            "DateBought": "2020/11/18 10:54",
            "DateExp": "2021-01-28",
            "Premium": 6.43,
            "AmtCost": 643,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 400,
            "StockTicker": "",
            "DateBought": "2020/11/18 10:55",
            "DateExp": "2021-03-30",
            "Premium": 2.8,
            "AmtCost": 280,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 400,
            "StockTicker": "",
            "DateBought": "2020/11/25 15:12",
            "DateExp": "2021-03-30",
            "Premium": 2.65,
            "AmtCost": 1060,
            "NumContract": -4,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 220,
            "StockTicker": "",
            "DateBought": "2020/11/30 9:41",
            "DateExp": "2021-01-28",
            "Premium": 2.54,
            "AmtCost": 254,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 220,
            "StockTicker": "",
            "DateBought": "2020/11/30 9:41",
            "DateExp": "2021-01-28",
            "Premium": 2.54,
            "AmtCost": 254,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 220,
            "StockTicker": "",
            "DateBought": "2020/11/30 9:41",
            "DateExp": "2021-01-28",
            "Premium": 2.52,
            "AmtCost": 252,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 220,
            "StockTicker": "",
            "DateBought": "2020/12/1 10:42",
            "DateExp": "2021-03-30",
            "Premium": 6.92,
            "AmtCost": 692,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 180,
            "StockTicker": "",
            "DateBought": "2020/12/1 10:44",
            "DateExp": "2021-09-29",
            "Premium": 7.6,
            "AmtCost": 760,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 200,
            "StockTicker": "",
            "DateBought": "2020/12/1 11:47",
            "DateExp": "2020-12-30",
            "Premium": 0.28,
            "AmtCost": 28,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 600,
            "StockTicker": "",
            "DateBought": "2020/12/2 10:14",
            "DateExp": "2021-01-28",
            "Premium": 18.6,
            "AmtCost": 1860,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 600,
            "StockTicker": "",
            "DateBought": "2020/12/2 10:14",
            "DateExp": "2021-01-28",
            "Premium": 19.5,
            "AmtCost": 1950,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 410,
            "StockTicker": "",
            "DateBought": "2020/12/2 11:04",
            "DateExp": "2021-06-29",
            "Premium": 5.92,
            "AmtCost": 592,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 410,
            "StockTicker": "",
            "DateBought": "2020/12/2 11:06",
            "DateExp": "2021-06-29",
            "Premium": 5.96,
            "AmtCost": 596,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 200,
            "StockTicker": "",
            "DateBought": "2020/12/2 11:46",
            "DateExp": "2021-03-30",
            "Premium": 3.53,
            "AmtCost": 353,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 200,
            "StockTicker": "",
            "DateBought": "2020/12/2 11:46",
            "DateExp": "2021-03-30",
            "Premium": 3.58,
            "AmtCost": 358,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 180,
            "StockTicker": "",
            "DateBought": "2020/12/4 10:38",
            "DateExp": "2021-09-29",
            "Premium": 6.08,
            "AmtCost": 608,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 380,
            "StockTicker": "",
            "DateBought": "2020/12/4 15:09",
            "DateExp": "2021-09-29",
            "Premium": 4.93,
            "AmtCost": 986,
            "NumContract": -2,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 192,
            "StockTicker": "",
            "DateBought": "2020/12/4 15:32",
            "DateExp": "2021-09-29",
            "Premium": 7.8,
            "AmtCost": 780,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 192,
            "StockTicker": "",
            "DateBought": "2020/12/4 15:33",
            "DateExp": "2021-09-29",
            "Premium": 7.8,
            "AmtCost": 780,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 380,
            "StockTicker": "",
            "DateBought": "2020/12/7 9:36",
            "DateExp": "2021-09-29",
            "Premium": 4.63,
            "AmtCost": 926,
            "NumContract": -2,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 480,
            "StockTicker": "",
            "DateBought": "2020/12/7 9:37",
            "DateExp": "2021-02-25",
            "Premium": 3.45,
            "AmtCost": 690,
            "NumContract": -2,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 440,
            "StockTicker": "",
            "DateBought": "2020/12/9 11:51",
            "DateExp": "2021-09-29",
            "Premium": 10.95,
            "AmtCost": 1095,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 440,
            "StockTicker": "",
            "DateBought": "2020/12/9 11:51",
            "DateExp": "2021-09-29",
            "Premium": 11,
            "AmtCost": 1100,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 400,
            "StockTicker": "",
            "DateBought": "2020/12/9 11:53",
            "DateExp": "2021-09-29",
            "Premium": 6.4,
            "AmtCost": 640,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 430,
            "StockTicker": "",
            "DateBought": "2020/12/9 11:55",
            "DateExp": "2021-06-29",
            "Premium": 5.4,
            "AmtCost": 540,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 430,
            "StockTicker": "",
            "DateBought": "2020/12/9 11:55",
            "DateExp": "2021-06-29",
            "Premium": 5.8,
            "AmtCost": 580,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 430,
            "StockTicker": "",
            "DateBought": "2020/12/9 11:56",
            "DateExp": "2021-06-29",
            "Premium": 5.6,
            "AmtCost": 560,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 270,
            "StockTicker": "",
            "DateBought": "2020/12/9 13:38",
            "DateExp": "2020-12-30",
            "Premium": 3.93,
            "AmtCost": 393,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 265,
            "StockTicker": "",
            "DateBought": "2020/12/10 9:34",
            "DateExp": "2020-12-30",
            "Premium": 3.5,
            "AmtCost": 350,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 265,
            "StockTicker": "",
            "DateBought": "2020/12/10 9:36",
            "DateExp": "2020-12-30",
            "Premium": 3.2,
            "AmtCost": 320,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 400,
            "StockTicker": "",
            "DateBought": "2020/12/10 10:05",
            "DateExp": "2021-09-29",
            "Premium": 6.11,
            "AmtCost": 611,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 400,
            "StockTicker": "",
            "DateBought": "2020/12/10 10:05",
            "DateExp": "2021-09-29",
            "Premium": 6.15,
            "AmtCost": 615,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 600,
            "StockTicker": "",
            "DateBought": "2020/12/10 10:22",
            "DateExp": "2020-12-30",
            "Premium": 7.8,
            "AmtCost": 780,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 600,
            "StockTicker": "",
            "DateBought": "2020/12/10 10:22",
            "DateExp": "2020-12-30",
            "Premium": 7.66,
            "AmtCost": 766,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 610,
            "StockTicker": "",
            "DateBought": "2020/12/11 11:15",
            "DateExp": "2020-12-30",
            "Premium": 5.8,
            "AmtCost": 580,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 560,
            "StockTicker": "",
            "DateBought": "2020/12/14 13:30",
            "DateExp": "2020-12-30",
            "Premium": 6.87,
            "AmtCost": 1374,
            "NumContract": -2,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 570,
            "StockTicker": "",
            "DateBought": "2020/12/14 13:30",
            "DateExp": "2020-12-30",
            "Premium": 10.74,
            "AmtCost": 1074,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 570,
            "StockTicker": "",
            "DateBought": "2020/12/16 10:41",
            "DateExp": "2020-12-30",
            "Premium": 10.1,
            "AmtCost": 1010,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 590,
            "StockTicker": "",
            "DateBought": "2020/12/18 12:23",
            "DateExp": "2020-12-30",
            "Premium": 5.25,
            "AmtCost": 525,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 560,
            "StockTicker": "",
            "DateBought": "2020/12/21 10:24",
            "DateExp": "2020-12-30",
            "Premium": 4.1,
            "AmtCost": 410,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 440,
            "StockTicker": "",
            "DateBought": "2020/12/21 13:22",
            "DateExp": "2021-09-29",
            "Premium": 10.48,
            "AmtCost": 1048,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 440,
            "StockTicker": "",
            "DateBought": "2020/12/21 13:22",
            "DateExp": "2021-09-29",
            "Premium": 10.45,
            "AmtCost": 1045,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 430,
            "StockTicker": "",
            "DateBought": "2020/12/21 13:24",
            "DateExp": "2021-06-29",
            "Premium": 4.66,
            "AmtCost": 466,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 430,
            "StockTicker": "",
            "DateBought": "2020/12/21 13:24",
            "DateExp": "2021-06-29",
            "Premium": 4.75,
            "AmtCost": 475,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 440,
            "StockTicker": "",
            "DateBought": "2020/12/21 14:33",
            "DateExp": "2021-09-29",
            "Premium": 10.56,
            "AmtCost": 1056,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 200,
            "StockTicker": "",
            "DateBought": "2020/12/29 10:15",
            "DateExp": "2021-03-30",
            "Premium": 7.9,
            "AmtCost": 790,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 180,
            "StockTicker": "",
            "DateBought": "2020/12/29 11:09",
            "DateExp": "2021-09-29",
            "Premium": 10.95,
            "AmtCost": 1095,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 500,
            "StockTicker": "",
            "DateBought": "2020/12/29 13:39",
            "DateExp": "2021-01-28",
            "Premium": 6.15,
            "AmtCost": 1230,
            "NumContract": -2,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 500,
            "StockTicker": "",
            "DateBought": "2020/12/29 13:40",
            "DateExp": "2021-02-25",
            "Premium": 10.76,
            "AmtCost": 2152,
            "NumContract": -2,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 500,
            "StockTicker": "",
            "DateBought": "2020/12/29 13:40",
            "DateExp": "2021-03-30",
            "Premium": 17.8,
            "AmtCost": 3560,
            "NumContract": -2,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 500,
            "StockTicker": "",
            "DateBought": "2020/12/29 13:41",
            "DateExp": "2021-06-29",
            "Premium": 29.66,
            "AmtCost": 5932,
            "NumContract": -2,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 610,
            "StockTicker": "",
            "DateBought": "2020/12/31 9:51",
            "DateExp": "2021-02-25",
            "Premium": 14.46,
            "AmtCost": 1446,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 610,
            "StockTicker": "",
            "DateBought": "2020/12/31 9:52",
            "DateExp": "2021-02-25",
            "Premium": 14.51,
            "AmtCost": 1451,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 245,
            "StockTicker": "",
            "DateBought": "2021/1/6 10:36",
            "DateExp": "2021-01-28",
            "Premium": 4,
            "AmtCost": 400,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 225,
            "StockTicker": "",
            "DateBought": "2021/1/13 9:57",
            "DateExp": "2021-01-28",
            "Premium": 8.2,
            "AmtCost": 820,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 580,
            "StockTicker": "",
            "DateBought": "2021/5/12 15:15",
            "DateExp": "2021-06-29",
            "Premium": 17.58,
            "AmtCost": 1758,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 560,
            "StockTicker": "",
            "DateBought": "2021/5/12 15:16",
            "DateExp": "2021-07-29",
            "Premium": 16,
            "AmtCost": 1600,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 600,
            "StockTicker": "",
            "DateBought": "2021/6/1 11:47",
            "DateExp": "2021-07-29",
            "Premium": 14.77,
            "AmtCost": 1477,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 600,
            "StockTicker": "",
            "DateBought": "2021/6/1 11:49",
            "DateExp": "2021-08-30",
            "Premium": 21.83,
            "AmtCost": 2183,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 590,
            "StockTicker": "",
            "DateBought": "2021/6/2 11:07",
            "DateExp": "2021-09-29",
            "Premium": 22.94,
            "AmtCost": 2294,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 550,
            "StockTicker": "",
            "DateBought": "2021/6/2 11:07",
            "DateExp": "2021-09-29",
            "Premium": 10.93,
            "AmtCost": 1093,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 540,
            "StockTicker": "",
            "DateBought": "2021/6/2 11:08",
            "DateExp": "2021-12-30",
            "Premium": 16.84,
            "AmtCost": 1684,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 590,
            "StockTicker": "",
            "DateBought": "2021/6/2 11:12",
            "DateExp": "2021-06-29",
            "Premium": 5.68,
            "AmtCost": 568,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 540,
            "StockTicker": "",
            "DateBought": "2021/6/4 13:47",
            "DateExp": "2021-12-30",
            "Premium": 19.04,
            "AmtCost": 1904,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 550,
            "StockTicker": "",
            "DateBought": "2021/6/4 13:48",
            "DateExp": "2021-09-29",
            "Premium": 12.6,
            "AmtCost": 1260,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 570,
            "StockTicker": "",
            "DateBought": "2021/6/7 11:15",
            "DateExp": "2021-08-30",
            "Premium": 16,
            "AmtCost": 1600,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 560,
            "StockTicker": "",
            "DateBought": "2021/6/7 11:16",
            "DateExp": "2021-08-30",
            "Premium": 12,
            "AmtCost": 1200,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 550,
            "StockTicker": "",
            "DateBought": "2021/6/7 11:18",
            "DateExp": "2021-12-30",
            "Premium": 23.5,
            "AmtCost": 2350,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 550,
            "StockTicker": "",
            "DateBought": "2021/6/7 11:18",
            "DateExp": "2021-12-30",
            "Premium": 22.76,
            "AmtCost": 2276,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 180,
            "StockTicker": "",
            "DateBought": "2021/6/7 11:20",
            "DateExp": "2021-12-30",
            "Premium": 7,
            "AmtCost": 3500,
            "NumContract": -1,
            "NumShareExposed": 500,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 580,
            "StockTicker": "",
            "DateBought": "2021/6/7 13:40",
            "DateExp": "2021-06-29",
            "Premium": 5.75,
            "AmtCost": 575,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 560,
            "StockTicker": "",
            "DateBought": "2021/6/7 13:41",
            "DateExp": "2021-07-29",
            "Premium": 6.83,
            "AmtCost": 683,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 630,
            "StockTicker": "",
            "DateBought": "2021/6/7 13:43",
            "DateExp": "2021-06-29",
            "Premium": 6.52,
            "AmtCost": 652,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 640,
            "StockTicker": "",
            "DateBought": "2021/6/7 13:43",
            "DateExp": "2021-06-29",
            "Premium": 4.95,
            "AmtCost": 495,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 660,
            "StockTicker": "",
            "DateBought": "2021/6/7 13:44",
            "DateExp": "2021-06-29",
            "Premium": 2.83,
            "AmtCost": 283,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 630,
            "StockTicker": "",
            "DateBought": "2021/6/7 14:20",
            "DateExp": "2021-06-29",
            "Premium": 6.18,
            "AmtCost": 618,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 480,
            "StockTicker": "",
            "DateBought": "2021/6/7 14:49",
            "DateExp": "2022-03-30",
            "Premium": 11.41,
            "AmtCost": 3423,
            "NumContract": -3,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 480,
            "StockTicker": "",
            "DateBought": "2021/6/7 14:49",
            "DateExp": "2021-12-30",
            "Premium": 7.4,
            "AmtCost": 2220,
            "NumContract": -3,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 480,
            "StockTicker": "",
            "DateBought": "2021/6/7 14:50",
            "DateExp": "2022-06-29",
            "Premium": 16.7,
            "AmtCost": 5010,
            "NumContract": -3,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 470,
            "StockTicker": "",
            "DateBought": "2021/6/7 14:51",
            "DateExp": "2022-03-30",
            "Premium": 9.76,
            "AmtCost": 1952,
            "NumContract": -2,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 162,
            "StockTicker": "",
            "DateBought": "2021/6/7 14:52",
            "DateExp": "2022-03-30",
            "Premium": 5.83,
            "AmtCost": 5830,
            "NumContract": -2,
            "NumShareExposed": 500,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 162,
            "StockTicker": "",
            "DateBought": "2021/6/7 14:52",
            "DateExp": "2022-03-30",
            "Premium": 5.83,
            "AmtCost": 5830,
            "NumContract": -2,
            "NumShareExposed": 500,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 170,
            "StockTicker": "",
            "DateBought": "2021/6/8 15:32",
            "DateExp": "2022-03-30",
            "Premium": 7.74,
            "AmtCost": 3870,
            "NumContract": -1,
            "NumShareExposed": 500,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 170,
            "StockTicker": "",
            "DateBought": "2021/6/8 15:32",
            "DateExp": "2022-03-30",
            "Premium": 7.74,
            "AmtCost": 3870,
            "NumContract": -1,
            "NumShareExposed": 500,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 170,
            "StockTicker": "",
            "DateBought": "2021/6/8 15:33",
            "DateExp": "2022-06-29",
            "Premium": 10.63,
            "AmtCost": 5315,
            "NumContract": -1,
            "NumShareExposed": 500,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "阿里",
            "Strike": 180,
            "StockTicker": "",
            "DateBought": "2021/6/10 10:03",
            "DateExp": "2021-12-30",
            "Premium": 6.84,
            "AmtCost": 6840,
            "NumContract": -2,
            "NumShareExposed": 500,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "騰訊",
            "Strike": 620,
            "StockTicker": "",
            "DateBought": "2021/6/11 10:30",
            "DateExp": "2021-06-29",
            "Premium": 5.8,
            "AmtCost": 580,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },

        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "FU",
            "Strike": 146,
            "StockTicker": "",
            "DateBought": "2021/6/9 9:56",
            "DateExp": "2021-06-25",
            "Premium": 8.4,
            "AmtCost": 840,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "FU",
            "Strike": 150,
            "StockTicker": "",
            "DateBought": "2021/6/8 9:38",
            "DateExp": "2021-06-18",
            "Premium": 6.5,
            "AmtCost": 650,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "FU",
            "Strike": 165,
            "StockTicker": "",
            "DateBought": "2021/6/4 9:39",
            "DateExp": "2021-06-25",
            "Premium": 4.6,
            "AmtCost": 920,
            "NumContract": -2,
            "NumShareExposed": 100,
            "P_C": "C",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "BA",
            "Strike": 205,
            "StockTicker": "",
            "DateBought": "2020/11/12 11:11",
            "DateExp": "2020-12-11",
            "Premium": 1.05,
            "AmtCost": 105,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        },
        {
            "Id": -1,
            "Status": 0,
            "Remark": "",
            "UpdateBy": 0,
            "Name": "BA",
            "Strike": 220,
            "StockTicker": "",
            "DateBought": "2020/11/12 9:50",
            "DateExp": "2020-12-11",
            "Premium": 2.12,
            "AmtCost": 212,
            "NumContract": -1,
            "NumShareExposed": 100,
            "P_C": "P",
            "_dirty": true
        }
    ]
;