OPTIONS_JSON =
    [{
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 購",
        "StockTicker": "",
        "DateBought": "2020/11/12 14:47",
        "DateExp": "20201127",
        "Premium": 18,
        "NumContract": -1,
        "NumShareExposed": 0.05555555555555555,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/11/12 14:58",
        "DateExp": "20201230",
        "Premium": 2,
        "NumContract": -1,
        "NumShareExposed": 114.5,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 購",
        "StockTicker": "",
        "DateBought": "2020/11/12 15:24",
        "DateExp": "20201127",
        "Premium": 18,
        "NumContract": 1,
        "NumShareExposed": 0.05555555555555555,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/11/13 14:36",
        "DateExp": "20210629",
        "Premium": 8,
        "NumContract": -3,
        "NumShareExposed": 0.08333333333333333,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 購",
        "StockTicker": "",
        "DateBought": "2020/11/13 15:20",
        "DateExp": "20201127",
        "Premium": 8,
        "NumContract": -1,
        "NumShareExposed": 102.875,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/11/16 10:10",
        "DateExp": "20201230",
        "Premium": 2,
        "NumContract": -1,
        "NumShareExposed": 118,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/11/16 10:11",
        "DateExp": "20201127",
        "Premium": 1,
        "NumContract": -1,
        "NumShareExposed": 102,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/11/16 11:52",
        "DateExp": "20210225",
        "Premium": 7,
        "NumContract": -1,
        "NumShareExposed": 108.28571428571429,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/11/17 9:48",
        "DateExp": "20210629",
        "Premium": 5,
        "NumContract": -2,
        "NumShareExposed": 0.1,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/11/17 9:49",
        "DateExp": "20210629",
        "Premium": 5,
        "NumContract": -1,
        "NumShareExposed": 119.4,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/11/17 13:37",
        "DateExp": "20210629",
        "Premium": 6,
        "NumContract": -1,
        "NumShareExposed": 109.5,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/11/18 10:54",
        "DateExp": "20210128",
        "Premium": 6,
        "NumContract": -1,
        "NumShareExposed": 107.16666666666667,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/11/18 10:55",
        "DateExp": "20210330",
        "Premium": 2,
        "NumContract": -1,
        "NumShareExposed": 140,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/11/25 15:12",
        "DateExp": "20210330",
        "Premium": 2,
        "NumContract": -4,
        "NumShareExposed": 0.125,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/11/30 9:41",
        "DateExp": "20210128",
        "Premium": 2,
        "NumContract": -1,
        "NumShareExposed": 127,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/11/30 9:41",
        "DateExp": "20210128",
        "Premium": 2,
        "NumContract": -1,
        "NumShareExposed": 127,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/11/30 9:41",
        "DateExp": "20210128",
        "Premium": 2,
        "NumContract": -1,
        "NumShareExposed": 126,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/1 10:42",
        "DateExp": "20210330",
        "Premium": 6,
        "NumContract": -1,
        "NumShareExposed": 115.33333333333333,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/1 10:44",
        "DateExp": "20210929",
        "Premium": 7,
        "NumContract": -1,
        "NumShareExposed": 108.57142857142857,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/1 11:47",
        "DateExp": "20201230",
        "Premium": 0,
        "NumContract": -1,
        "NumShareExposed": null,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 購",
        "StockTicker": "",
        "DateBought": "2020/12/2 10:14",
        "DateExp": "20210128",
        "Premium": 18,
        "NumContract": -1,
        "NumShareExposed": 0.05555555555555555,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 購",
        "StockTicker": "",
        "DateBought": "2020/12/2 10:14",
        "DateExp": "20210128",
        "Premium": 19,
        "NumContract": -1,
        "NumShareExposed": 0.05263157894736842,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/2 11:04",
        "DateExp": "20210629",
        "Premium": 5,
        "NumContract": -1,
        "NumShareExposed": 118.4,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/2 11:06",
        "DateExp": "20210629",
        "Premium": 5,
        "NumContract": -1,
        "NumShareExposed": 119.2,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/2 11:46",
        "DateExp": "20210330",
        "Premium": 3,
        "NumContract": -1,
        "NumShareExposed": 117.66666666666667,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/2 11:46",
        "DateExp": "20210330",
        "Premium": 3,
        "NumContract": -1,
        "NumShareExposed": 119.33333333333333,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/4 10:38",
        "DateExp": "20210929",
        "Premium": 6,
        "NumContract": -1,
        "NumShareExposed": 101.33333333333333,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/4 15:09",
        "DateExp": "20210929",
        "Premium": 4,
        "NumContract": -2,
        "NumShareExposed": 123.25,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/4 15:32",
        "DateExp": "20210929",
        "Premium": 7,
        "NumContract": -1,
        "NumShareExposed": 111.42857142857143,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/4 15:33",
        "DateExp": "20210929",
        "Premium": 7,
        "NumContract": -1,
        "NumShareExposed": 111.42857142857143,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/7 9:36",
        "DateExp": "20210929",
        "Premium": 4,
        "NumContract": -2,
        "NumShareExposed": 115.75,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/7 9:37",
        "DateExp": "20210225",
        "Premium": 3,
        "NumContract": -2,
        "NumShareExposed": 115,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/9 11:51",
        "DateExp": "20210929",
        "Premium": 10,
        "NumContract": -1,
        "NumShareExposed": 0.1,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/9 11:51",
        "DateExp": "20210929",
        "Premium": 11,
        "NumContract": -1,
        "NumShareExposed": 0.09090909090909091,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/9 11:53",
        "DateExp": "20210929",
        "Premium": 6,
        "NumContract": -1,
        "NumShareExposed": 106.66666666666667,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/9 11:55",
        "DateExp": "20210629",
        "Premium": 5,
        "NumContract": -1,
        "NumShareExposed": 108,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/9 11:55",
        "DateExp": "20210629",
        "Premium": 5,
        "NumContract": -1,
        "NumShareExposed": 116,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/9 11:56",
        "DateExp": "20210629",
        "Premium": 5,
        "NumContract": -1,
        "NumShareExposed": 112,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 購",
        "StockTicker": "",
        "DateBought": "2020/12/9 13:38",
        "DateExp": "20201230",
        "Premium": 3,
        "NumContract": -1,
        "NumShareExposed": 131,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 購",
        "StockTicker": "",
        "DateBought": "2020/12/10 9:34",
        "DateExp": "20201230",
        "Premium": 3,
        "NumContract": -1,
        "NumShareExposed": 116.66666666666667,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 購",
        "StockTicker": "",
        "DateBought": "2020/12/10 9:36",
        "DateExp": "20201230",
        "Premium": 3,
        "NumContract": -1,
        "NumShareExposed": 106.66666666666667,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/10 10:05",
        "DateExp": "20210929",
        "Premium": 6,
        "NumContract": -1,
        "NumShareExposed": 101.83333333333333,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/10 10:05",
        "DateExp": "20210929",
        "Premium": 6,
        "NumContract": -1,
        "NumShareExposed": 102.5,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 購",
        "StockTicker": "",
        "DateBought": "2020/12/10 10:22",
        "DateExp": "20201230",
        "Premium": 7,
        "NumContract": -1,
        "NumShareExposed": 111.42857142857143,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 購",
        "StockTicker": "",
        "DateBought": "2020/12/10 10:22",
        "DateExp": "20201230",
        "Premium": 7,
        "NumContract": -1,
        "NumShareExposed": 109.42857142857143,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 購",
        "StockTicker": "",
        "DateBought": "2020/12/11 11:15",
        "DateExp": "20201230",
        "Premium": 5,
        "NumContract": -1,
        "NumShareExposed": 116,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/14 13:30",
        "DateExp": "20201230",
        "Premium": 6,
        "NumContract": -2,
        "NumShareExposed": 0.08333333333333333,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/14 13:30",
        "DateExp": "20201230",
        "Premium": 10,
        "NumContract": -1,
        "NumShareExposed": 0.1,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 購",
        "StockTicker": "",
        "DateBought": "2020/12/16 10:41",
        "DateExp": "20201230",
        "Premium": 10,
        "NumContract": -1,
        "NumShareExposed": 0.1,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 購",
        "StockTicker": "",
        "DateBought": "2020/12/18 12:23",
        "DateExp": "20201230",
        "Premium": 5,
        "NumContract": -1,
        "NumShareExposed": 105,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/21 10:24",
        "DateExp": "20201230",
        "Premium": 4,
        "NumContract": -1,
        "NumShareExposed": 102.5,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/21 13:22",
        "DateExp": "20210929",
        "Premium": 10,
        "NumContract": -1,
        "NumShareExposed": 0.1,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/21 13:22",
        "DateExp": "20210929",
        "Premium": 10,
        "NumContract": -1,
        "NumShareExposed": 0.1,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/21 13:24",
        "DateExp": "20210629",
        "Premium": 4,
        "NumContract": -1,
        "NumShareExposed": 116.5,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/21 13:24",
        "DateExp": "20210629",
        "Premium": 4,
        "NumContract": -1,
        "NumShareExposed": 118.75,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/21 14:33",
        "DateExp": "20210929",
        "Premium": 10,
        "NumContract": -1,
        "NumShareExposed": 0.1,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/29 10:15",
        "DateExp": "20210330",
        "Premium": 7,
        "NumContract": -1,
        "NumShareExposed": 112.85714285714286,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/29 11:09",
        "DateExp": "20210929",
        "Premium": 10,
        "NumContract": -1,
        "NumShareExposed": 0.1,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/29 13:39",
        "DateExp": "20210128",
        "Premium": 6,
        "NumContract": -2,
        "NumShareExposed": 0.08333333333333333,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/29 13:40",
        "DateExp": "20210225",
        "Premium": 10,
        "NumContract": -2,
        "NumShareExposed": 0.1,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/29 13:40",
        "DateExp": "20210330",
        "Premium": 17,
        "NumContract": -2,
        "NumShareExposed": 0.08823529411764706,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2020/12/29 13:41",
        "DateExp": "20210629",
        "Premium": 29,
        "NumContract": -2,
        "NumShareExposed": 0.08620689655172414,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 購",
        "StockTicker": "",
        "DateBought": "2020/12/31 9:51",
        "DateExp": "20210225",
        "Premium": 14,
        "NumContract": -1,
        "NumShareExposed": 0.07142857142857142,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 購",
        "StockTicker": "",
        "DateBought": "2020/12/31 9:52",
        "DateExp": "20210225",
        "Premium": 14,
        "NumContract": -1,
        "NumShareExposed": 0.07142857142857142,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 購",
        "StockTicker": "",
        "DateBought": "2021/1/6 10:36",
        "DateExp": "20210128",
        "Premium": 4,
        "NumContract": -1,
        "NumShareExposed": 100,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 購",
        "StockTicker": "",
        "DateBought": "2021/1/13 9:57",
        "DateExp": "20210128",
        "Premium": 8,
        "NumContract": -1,
        "NumShareExposed": 102.5,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/5/12 15:15",
        "DateExp": "20210629",
        "Premium": 17,
        "NumContract": -1,
        "NumShareExposed": 0.058823529411764705,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/5/12 15:16",
        "DateExp": "20210729",
        "Premium": 16,
        "NumContract": -1,
        "NumShareExposed": 0.0625,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/1 11:47",
        "DateExp": "20210729",
        "Premium": 14,
        "NumContract": -1,
        "NumShareExposed": 0.07142857142857142,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/1 11:49",
        "DateExp": "20210830",
        "Premium": 21,
        "NumContract": -1,
        "NumShareExposed": 0.09523809523809523,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/2 11:07",
        "DateExp": "20210929",
        "Premium": 22,
        "NumContract": -1,
        "NumShareExposed": 0.09090909090909091,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/2 11:07",
        "DateExp": "20210929",
        "Premium": 10,
        "NumContract": -1,
        "NumShareExposed": 0.1,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/2 11:08",
        "DateExp": "20211230",
        "Premium": 16,
        "NumContract": -1,
        "NumShareExposed": 0.0625,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/2 11:12",
        "DateExp": "20210629",
        "Premium": 5,
        "NumContract": -1,
        "NumShareExposed": 113.6,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/4 13:47",
        "DateExp": "20211230",
        "Premium": 19,
        "NumContract": -1,
        "NumShareExposed": 0.05263157894736842,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/4 13:48",
        "DateExp": "20210929",
        "Premium": 12,
        "NumContract": -1,
        "NumShareExposed": 0.08333333333333333,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/7 11:15",
        "DateExp": "20210830",
        "Premium": 16,
        "NumContract": -1,
        "NumShareExposed": 0.0625,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/7 11:16",
        "DateExp": "20210830",
        "Premium": 12,
        "NumContract": -1,
        "NumShareExposed": 0.08333333333333333,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/7 11:18",
        "DateExp": "20211230",
        "Premium": 23,
        "NumContract": -1,
        "NumShareExposed": 0.08695652173913043,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/7 11:18",
        "DateExp": "20211230",
        "Premium": 22,
        "NumContract": -1,
        "NumShareExposed": 0.09090909090909091,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/7 11:20",
        "DateExp": "20211230",
        "Premium": 7,
        "NumContract": -1,
        "NumShareExposed": 0.42857142857142855,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/7 13:40",
        "DateExp": "20210629",
        "Premium": 5,
        "NumContract": -1,
        "NumShareExposed": 115,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/7 13:41",
        "DateExp": "20210729",
        "Premium": 6,
        "NumContract": -1,
        "NumShareExposed": 113.83333333333333,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 購",
        "StockTicker": "",
        "DateBought": "2021/6/7 13:43",
        "DateExp": "20210629",
        "Premium": 6,
        "NumContract": -1,
        "NumShareExposed": 108.66666666666667,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 購",
        "StockTicker": "",
        "DateBought": "2021/6/7 13:43",
        "DateExp": "20210629",
        "Premium": 4,
        "NumContract": -1,
        "NumShareExposed": 123.75,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 購",
        "StockTicker": "",
        "DateBought": "2021/6/7 13:44",
        "DateExp": "20210629",
        "Premium": 2,
        "NumContract": -1,
        "NumShareExposed": 141.5,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 購",
        "StockTicker": "",
        "DateBought": "2021/6/7 14:20",
        "DateExp": "20210629",
        "Premium": 6,
        "NumContract": -1,
        "NumShareExposed": 103,
        "P_C": "C",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/7 14:49",
        "DateExp": "20220330",
        "Premium": 11,
        "NumContract": -3,
        "NumShareExposed": 0.0909090909090909,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/7 14:49",
        "DateExp": "20211230",
        "Premium": 7,
        "NumContract": -3,
        "NumShareExposed": 0.09523809523809523,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/7 14:50",
        "DateExp": "20220629",
        "Premium": 16,
        "NumContract": -3,
        "NumShareExposed": 0.10416666666666667,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/7 14:51",
        "DateExp": "20220330",
        "Premium": 9,
        "NumContract": -2,
        "NumShareExposed": 0.05555555555555555,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/7 14:52",
        "DateExp": "20220330",
        "Premium": 5,
        "NumContract": -2,
        "NumShareExposed": 0.5,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/7 14:52",
        "DateExp": "20220330",
        "Premium": 5,
        "NumContract": -2,
        "NumShareExposed": 0.5,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/8 15:32",
        "DateExp": "20220330",
        "Premium": 7,
        "NumContract": -1,
        "NumShareExposed": 0.42857142857142855,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/8 15:32",
        "DateExp": "20220330",
        "Premium": 7,
        "NumContract": -1,
        "NumShareExposed": 0.42857142857142855,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/8 15:33",
        "DateExp": "20220629",
        "Premium": 10,
        "NumContract": -1,
        "NumShareExposed": 0.5,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "阿里 2 沽",
        "StockTicker": "",
        "DateBought": "2021/6/10 10:03",
        "DateExp": "20211230",
        "Premium": 6,
        "NumContract": -2,
        "NumShareExposed": 0.5,
        "P_C": "P",
        "_dirty": true
    }, {
        "Id": -1,
        "Status": 0,
        "Remark": "",
        "UpdateBy": 0,
        "Name": "騰訊 2 購",
        "StockTicker": "",
        "DateBought": "2021/6/11 10:30",
        "DateExp": "20210629",
        "Premium": 5,
        "NumContract": -1,
        "NumShareExposed": 116,
        "P_C": "C",
        "_dirty": true
    }]